version: "3"
services:
  db:
    image: "mariadb:latest"
    ports:
      - ${DB_HOST_PORT}:3306
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysqldata:/var/lib/mysql

  app:
    image: "wordpress:latest"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}
      WORDPRESS_DEBUG: ${WP_DEBUG}
    ports:
      - ${WP_HOST_PORT}:80
    depends_on:
      - db
    volumes:
      - ../public:/var/www/html
      - ./dev-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  mysqldata:
    driver: local
